project:
  type: book

book:
  title: "A Lecture on Topological Operators"
  author:
    - name: Kantaro Ohmori
      emal: kant.ohmori@gmail.com
      affiliations:
        - name: The University of Tokyo
          department: Faculty of Sciences
          address: Hongo 7-3-1
          city: Tokyo
          country: Japan
          postal-code: 113-8654
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - scalar.qmd
    - vector.qmd
    - summary.qmd
    - references.qmd
  downloads: pdf
  body-header: header.qmd
    

number-sections: true
shift-heading-level-by: 0

bibliography: references.bib


format:
  html:
    theme: cosmo
    csl: american-statistical-association.csl
    anchor-sections: true
  pdf:
    documentclass: scrreport
    cite-method: biblatex
    biblatexoptions: 
      - "style=phys"
      - "eprint=true"
      - "url=true"
      - "backref=true"
      - "biblabel=brackets"
      - "citestyle = numeric-comp"
      - "sorting = none"
    filters:
      - line-break.lua
      - callout-title-modify.lua
    keep-tex: true
    fig-pos: 't'
    include-in-header: header.tex

callout-icon: true


