# Introduction

## Symmetry
**Symmetry** plays a fundamental role in theoretical physics. 
In this lecture we consider them in *quantum field theories* (QFTs). 
The fundamental fact about symmetry in QFTs is that is it preserved along the renormalization group flow.
More precisely, when an ultraviolet (UV) theory $\mathcal{T}_\text{UV}$ flows into an infrared theory $\mathcal{T}_\text{IR}$, there is a canonical homomorphism $f_\text{RG}$ from the UV symmetry group $G_\text{UV}$ to the IR symmetry group $G_\text{IR}$:[^SymRG]

::: {.callout-note icon="false"}
## RG flow homomorphism from UV symmetry to IR symmetry
$$
f_\text{RG} : G_\text{UV} \to G_\text{IR}.
$${#eq-RG-group-match}
:::


Given this relation, there are two ways of applying symmetry in QFT:

* UV to IR: Given a microscopic model (e.g. a model of elementary particles or electrons in a matter), constrain/guess what happens in the macroscopic scale.
* IR to UV: Given some macroscopic phenomena, constrain/guess what could be the microscopic origin of it (e.g. guessing QCD lagrangian from hadron spectrum).

[^SymRG]: If the UV theory is a fixed point, $G_\text{UV}$ should be understood as the one preserved by the perturbation triggering the RG flow. If the RG flow is to a lower nonzero energy, and if one retains all the (even very massive) degrees of freedom in the description of $\mathcal{T}_\text{IR}$, the map $f_\text{RG}$ is an isomorphism.
However, typically one integrates out massive dofs in the description of $\mathcal{T}_\text{RG}$, in which case some symmetry can decouple and thus $f_\text{RG}$ can be non-surjective. Also, if one also drops some higher-order interaction terms, or runs the flow to the zero energy, there can be an *emergent* symmetry, in which case $f_\text{RG}$ can be non-injective.

::: {.callout-warning}
In this lecture, whenever something is called "symmetry", it means a *global* symmetry.
Here *global* means that the symmetry operation acts on the entire space. In addition, in most contents we exclude symmetries acting on the spacetime out of consideration for simplicity.
:::

## Locality
The second important keyword in this lecture is **locality**.
By the word quantum field theory, in most cases we implicitly mean *local* quantum field theory.
This can roughly be explain that the action is written as the integration of Lagrangian density, which is a local functional of fields over the spacetime.

Locality of QFT has a concequence with respect to symmetry: that is, in most situations we only consider symmetries that *preserves locality*. 
In terms of fields, this means that the symmetry transformation is local:

$$
\phi(x) \mapsto F(\phi(x)),
$${#eq-field-transform}
where $F(\phi(x))$ is a function depends on the *local* value a field (or a collection of fields and its derivatives) at the point $x$.
If the symmetry involves a spacetime transformation, the point $x$ in the right hand side should be replaced by the image of $x$ under the symmetry.
This preservation of locality of a symmetry is the reason for the symmetry relation in @eq-RG-group-match.
This will be made clear in the lecture.

However, not all the (locality-preserving) symmetry in QFT takes the form of @eq-field-transform. 
There are types of symmetry called "topological symmetry", which arises from topologically-nontrivial field configuration.
Examples are the winding symmetry in 1+1d compact boson, and the monopole symmetries in 2+1d abelian gauge theories.
In many occurences a topological symmetry is mapped to a symmetry of type of @eq-field-transform under a duality, and thus it should also be considered as being locality-preserving.

From the modern perspective, the universal charactarization of locality-preserving symmetry is its correspondence to **topological operators**.

::: {.callout-warning}
Again, we are *not* talking about gauge redundancy, which is sometimes called local symmetry. Global symmetries one encounters in a QFT textbook are all locality preserving.
:::

::: {.callout-warning}
Here is another unfortunate conflict of terminology. In the literature (outside of generalized symmetry literature), a "topological defect" refers to a dynamical object, or its trajectory viewed as an operator in the IR theory, charg**ed** under a topological (higher) symmetry. In this lecture (and widely in the generalized symmetry literature) "topological defect operator" means an extended operator that is itself topological.
:::